### ISSUE TITLE
Version change and API cannot be used any more

### ISSUE THREAD

**Issue by AnotherGoogleFans** [throttled/throttled#16]
func IntervalThrottleHandler(h http.Handler) http.Handler {
	th := throttled.Interval(
		throttled.PerMin(1),
		0,
		&throttled.VaryBy{Path: true},
		0,
	)
	return th.Throttle(h)
}

This works with old version. But with new version , undefined: throttled.Interval

**Comment by brandur** [comment]
Hi @AnotherGoogleFans,

As detailed in #9, we did a relatively recent major overhaul to the Throttled interface. You should be able to continue using the original by locking to V1 with this import path: `gopkg.in/throttled/throttled.v1`

That said, we would recommend that you upgrade to V2 given that we feel that it's a better designed interface and that it's unlikely to change in a major way again anytime soon. [This documentation example](https://godoc.org/gopkg.in/throttled/throttled.v2#example-HTTPRateLimiter) is very close to what you're trying to do, and a few tweaks to your code above should get you back to where you were.

Sorry about the churn! I'm closing this out now, but let me know if you have any other thoughts/concerns. Thanks!
