### ISSUE TITLE
Remove 0value.com link in description

### ISSUE THREAD

**Issue by aaronkavlie-wf** [throttled/throttled#17]
This repo has a prominent link to a blog post at 0value.com in the description.
The README explains that this describes the 1.x version though, and 2.x made major API changes.

The description should link to the godoc (or an updated blog post/tutorial if there is one).

**Comment by brandur** [comment]
@aaronkavlie-wf Is your main problem with it just that it's easy to misclick and get bad information? I think that it's presence is nominally positive in that it gives some background history of the project, and may be helpful for anyone trying to upgrade from the 1.x series, although I acknowledge that this will become less useful over time.

There are two other fairly prominent links to Godoc already (the badge at the top and the link under the "documentation" header).

**Comment by aaronkavlie-wf** [comment]
Yeah, or more precisely *outdated* information.

I was reading it over thinking it looked like a good overview of how to use the library, only to find out in the README that I couldn't rely on it.

**Comment by brandur** [comment]
Cool. Looking at the notes again, it's been almost a year since the interface was overhauled and we went to 2.x. As such, I'm okay removing the notes for the 1.x series. Done in 9de1df6.

**Comment by aaronkavlie-wf** [comment]
I was actually referring to the description at the top, which still has the link:

![screen shot 2016-06-27 at 12 37 11 pm](https://cloud.githubusercontent.com/assets/7768348/16393043/f6012754-3c63-11e6-8b26-2f5a72285a3a.png)

**Comment by brandur** [comment]
Ah, I see.

Alright, I've changed the description of the project to the first line of the README and killed the website link.
