### ISSUE TITLE
Should the "peek" feature be setting the "RetryAfter" field?

### ISSUE THREAD

**Issue by kidoman** [throttled/throttled#18]
I was hoping to answer questions preemptively about whether a request would be rate limited, by utilising the "peek" feature. However, the only field currently set is "ResetAfter". Thoughts?

**Comment by kidoman** [comment]
Reading the code in further detail explained why this is not possible.

**Comment by brandur** [comment]
@kidoman Hey Karan! Looks like you got this already, but I'm glad that it's figured out :)
