### ISSUE TITLE
Add option to `HTTPRateLimiter` to avoid writing X-RateLimit-* headers

### ISSUE THREAD

**Issue by nvartolomei** [throttled/throttled#19]
I have an use-case where throttling is done per service and is intended for api gateway. In case a service is overloaded it failovers to next backend. In this case api consumers would be confused by X-RateLimit-* headers set by throttled package.

Instead of writing custom middleware for api gateway that removes these headers I would like to avoid writing them at all.

A bool flag to `HTTPRateLimiter` would be enough.

What do you think? I can help with a PR for this.

**Comment by brandur** [comment]
@nvartolomei I think that would be quite a reasonable option. It's probably a good idea not to go too wild with options, but this one seems quite reasonable.

@metcalf Any additional thoughts?

> What do you think? I can help with a PR for this.

Sounds good. Thanks!

**Comment by metcalf** [comment]
HTTPRateLimiter is a pretty thin convenience wrapper. Given that the
implementation is ~20 lines I'd probably favor implementing your own
version of it over adding options to it. I had imagined that anyone wanting
to use throttled in a production system would eventually go down this road
anyway so they could fully customize the integration. I'm not strongly
opposed to adding a boolean option here but I'm not convinced it's better
than encouraging people to take HTTPRateLimiter as an example for their own
usage of the core throttled limiters.

**Comment by nvartolomei** [comment]
@metcalf I think I will go second route, in case this issue arises again you can think of adding this option.
