### ISSUE TITLE
Rate Limits by User

### ISSUE THREAD

**Issue by genexp** [throttled/throttled#23]
Hey Team - We have an API each user can potentially have their own rate limit.  Most users fall under the same one, but the API is pay-for-usage so it's important that we have a flexible rate limiter.  We'd like to write a custom middleware that does something like:

  * Get rate limit from JWT
  * Instantiate new limiter for user using previously instantiated redis connection
  * Check the limiter
  * Destroy the limiter

This is done on each request, and done quite frequently (100 reqs/sec).  I'm just wondering if anyone sees a conceptual problem with this.

Thanks for lovely software :)

**Comment by metcalf** [comment]
I don't forsee any issues at that request volume. The `GCRARateLimiter` is a small struct and initialization involves simple math. You'll GC the object on every request but I suspect it won't be a noticeable performance penalty compared to servicing the actual request. I would suggest storing and re-using the `GCRAStore` object between requests, no need to rebuild that every time.

**Comment by brandur** [comment]
Great answer @metcalf! Seconded.
