### ISSUE TITLE
Ruby port

### ISSUE THREAD

**Issue by meeee** [throttled/throttled#24]
I ported throttled to Ruby: https://github.com/Barzahlen/gcra-ruby (the [algorithm](https://github.com/Barzahlen/gcra-ruby/blob/master/lib/gcra/rate_limiter.rb) only, no Rack middleware).

The data format is compatible with throttled, so you can count both Go and Ruby applications against the same limit.

If you want, I'd be happy if you'd add a link to the throttled README.

**Comment by brandur** [comment]
Hi @meeee, very cool project!

I'd suggest that we start to maintain another top-level repo within throttled that contains links to other related projects and other information. I've taken the liberty to [create it here](https://github.com/throttled/gcra) and issue a [PR back to throttled's README](https://github.com/throttled/throttled/pull/25).

**Comment by meeee** [comment]
Great idea, thanks!
