### ISSUE TITLE
Custom VaryBy deprecated, how to replace it?

### ISSUE THREAD

**Issue by vad** [throttled/throttled#30]
Hi,
i see [here](https://godoc.org/gopkg.in/throttled/throttled.v2#RateLimit) that the custom function is deprecated. I'd like to rate limit based on something I must compute. Is there another way to do it?

Thanks :smiley:

**Comment by brandur** [comment]
Hi @vad,

It's pretty easy to miss, but `VaryBy` field on `HTTPRateLimiter` is actually an interface:

``` go
// HTTPRateLimiter faciliates using a Limiter to limit HTTP requests.
type HTTPRateLimiter struct {
	...

	// VaryBy is called for each request to generate a key for the
	// limiter. If it is nil, all requests use an empty string key.
	VaryBy interface {
		Key(*http.Request) string
	}
}
```

The `VaryBy` struct implements it, but you can just as easily make your own implementation:

``` go
type CustomVaryBy struct {
}

func (vb *CusomVaryBy) Key(r *http.Request) string {
	return "whatever I want"
}
```

I hope that helps! Good luck.

**Comment by vad** [comment]
@brandur thanks, very nice :+1:
