### ISSUE TITLE
Set quota per path (or any other criteria)

### ISSUE THREAD

**Issue by ArnoSen** [throttled/throttled#43]
I am looking for a rate limiter where I can set quota's per path.
I checked the source of this project but this looks like this is not straightforward.

Is this maybe on your roadmap or would you have any suggestions how this can be implemented elegantly?

**Comment by ArnoSen** [comment]
I already came up with a solution but would like to get confirmation on one thing.

can a store (I use memstore) be shared safely between rate limiters?

**Comment by brandur** [comment]
> can a store (I use memstore) be shared safely between rate limiters?

Yep! The whole system is designed to work across any number of nodes, each of which will be instantiating its own rate limiter.
