### ISSUE TITLE
expects import

### ISSUE THREAD

**Issue by 417806161** [throttled/throttled#44]
i have a question ,i build the throttled.v2 but it doesnot work
`code in directory /home/timliu/go/src/gopkg.in/throttled/throttled.v2 expects import "github.com/throttled/throttled"
app/server.go:14:2: code in directory /home/timliu/go/src/gopkg.in/throttled/throttled.v2/store/memstore expects import "github.com/throttled/throttled/store/memstore"
`
that is the error ,i don't know what happening,i hope you can tell me how to fix it .
thank you

**Comment by brandur** [comment]
Hey @417806161, see #31 and #32 for details, but a while back we dropped the use of `gopkg.in` for the project.

To fix this, you should be able to just `rm -rf` everything you have at `/home/timliu/go/src/gopkg.in/throttled/`, and then just do a fresh `go get` to get the updated depedency:

```
go get -u github.com/throttled/throttled
```

I'm going to close this out for now, but let us know if you're still having trouble.
