### ISSUE TITLE
Inaccurate reset header

### ISSUE THREAD

**Issue by montanaflynn** [throttled/throttled#55]
I'm trying to use throttled to set rate limit by hour like so:

`quota := throttled.RateQuota{throttled.PerHour(60 * 60), 5}`

When I hit the limit I get this response:

```http
HTTP/1.1 429 Too Many Requests
Content-Type: text/plain; charset=utf-8
Retry-After: 1
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 6
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 6
Date: Tue, 16 Apr 2019 09:17:33 GMT
Content-Length: 15

limit exceeded
```

But I can make a request before the `X-Ratelimit-Reset` value of 6 seconds and it will go through.

**Comment by brandur** [comment]
Hey @montanaflynn, I think this is just a misunderstanding in the interface.

The `X-RateLimit-Reset` header as used here and places like GitHub is the amount of time after which the rate resets *completely*, so in this case how long it'd take for the rate to get back to 6 (your max burst of 5 + 1).

You might be looking instead for `Retry-After` — that's the amount of time before you can make another request. You can see in your snippet above that it has a value of 1 second, and that's about the amount of time you'd have to wait for a new request to be allowed.

Closing this out, but let me know if this is still unclear.
