### ISSUE TITLE
[question] Python port permission

### ISSUE THREAD

**Issue by Jude188** [throttled/throttled#63]
Hi,
I'm considering starting to implement a Python port of this package. Python seems to be seriously lacking a solid rate limiting package that I can find with the only one that had any degree of maturity being abandoned some time ago. 

However, I noticed that your package is BSD-3 which means I need your permission to use the 'throttled' name (thinking of just calling it pythrottled). Would you guys be okay with this?

**Comment by brandur** [comment]
@Jude188 It's okay by me, but would definitely prefer it you used "pythrottled" for easier disambiguation on Google/GitHub/etc.

**Comment by Jude188** [comment]
Well, I made a start... Then I discovered there was an effort to make a Python package using GCRA almost exactly a year ago! And a very good effort too. I suspect that it makes more sense for us Python people to throw our weight behind that rather than muddy the water with more projects!

I'll leave a link to the project in case anyone comes across this and finds it useful or interesting.
https://github.com/sigmavirus24/rush

**Comment by brandur** [comment]
> I suspect that it makes more sense for us Python people to throw our weight behind that rather than muddy the water with more projects!

Good call! Don't write code when you don't have to :)

Thanks for following up. I'm going to close this issue, but let us know if there's anything else.
