### ISSUE TITLE
Client recommendations for consuming GCRA backed API?

### ISSUE THREAD

**Issue by schneems** [throttled/throttled#65]
Do you have a client recommendation for consuming an API that implements GCRA on the server?

**Comment by brandur** [comment]
Hey Richard, nice to hear from you!

Can you give us a few more details on the specifics of this particular situation — e.g., do you mean that the GCRA is implemented in a web server, or inside of a Redis instance? And you are trying to consume it over something like an HTTP/RPC/whatever API?

**Comment by schneems** [comment]
Hi! 👋 I got this repo link from your GCRA blog post, somehow completely missed that you were the author, hope you're doing well!

The full backstory is that I want to provide client rate throttling for the `platform-api` gem for the Heroku API. I've been casually poking at this problem for the last ~9ish months, yet it just now occurred to me to ask if there's some prior art in non-ruby languages (from the client-side).

I started out with a set of scripts, eventually developed a methodology for generating metrics for clients and then used that to systematically improve the client. 

- Original research, explains my methodology and process: https://github.com/schneems/rate_throttle_clients#how-to-write-a-rate-throttling-algorithm
- More recent, polished gem: https://github.com/zombocom/rate_throttle_client

In terms of GCRA implementation details. I don't think we've changed much since when you were working on the Heroku web API.

**Comment by brandur** [comment]
> hope you're doing well!

Yes, and same to you!

Ah — interesting stuff. So if I understand correctly, you've already got some smart client throttling strategies designed and working, but you're wondering if there might be a way to improve them by doing some kind of client-side coordination on rate through a centralized server?

If that it's, then we're a little beyond the scope of the throttled project unfortunately — this is more akin to what you have implemented server-side _in_ the Heroku API, with a basic rate limiting API and some optional HTTP scaffolding that can be used around it.

I don't have any direct experience with implementing client-side coordination, so I can only suggest the relatively obvious like choosing something that's lightweight, low overhead, and fast — you don't want to have to rate limit the rate limiting API!

I've often thought about trying to implement something like this in the Stripe API libraries. Although the basic mitigation after being rate limited is easy to figure out (make fewer requests), it gets _much_ harder if you have, say a client that knows they can do 100 RPS and wants to try to optimize to get as close to that number as possible. It's not too hard if you have just a single client/box, but as soon as you have many you get into difficult coordination problems.

**Comment by schneems** [comment]
Gotcha. Okay. If you ever want to look into this, it's an interest of mine. I'll work on moving forward with what i've got and i'll share if I get some additional info. 

> it gets much harder if you have, say a client that knows they can do 100 RPS and wants to try to optimize to get as close to that number as possible. It's not too hard if you have just a single client/box, but as soon as you have many you get into difficult coordination problems.

Exactly. I've spent the last ~9 months thinking about this and I think i've got a workable solution, but it's hard finding people who appreciate the difficulty or constraints to provide any feedback. The work is currently represented in https://github.com/zombocom/rate_throttle_client. 

If you find yourself in a position where you want to chat about this for the strip client, feel free to message me.
