### ISSUE TITLE
Redis DB should always be switched

### ISSUE THREAD

**Issue by reddec** [throttled/throttled#70]
Condition https://github.com/throttled/throttled/blob/608de1fa042e0b10dfa8a8298467bf5dc1e66367/store/redigostore/redigostore.go#L160

should also be applied even for DB=0, 'cause in a pool a previous connection user can change database to another.

Example:

1. Create pool (let's say with one connection only)
2. Get connection
3. Change to a database other than 0 (ex: 3)
5. Return connection back to pool
6. Create redigostore with DB=0
7. Try to use rate-limiter - 3 db will be used instead of 0

**Comment by brandur** [comment]
Thanks the report @reddec.

Fixed via #74.
