### ISSUE TITLE
Grammatical mistake within the configuration file creates an unclarity

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [throttled/throttled#92]
> SYSFS path for checking if the system is running on AC power

Construed strictly, the quoted line means: _if the system is running on AC power, then the path will be . ._ That is not what is meant. What is meant is:

> SYSFS path for checking whether the system is running on AC power

**Comment by brandur** [comment]
@LinuxOnTheDesktop Do you have the wrong repository?

Closing this out.
