### ISSUE TITLE
Is there a plan to upgrade github.com/go-redis/redis to latest 

### ISSUE THREAD

**Issue by cpratap994** [throttled/throttled#96]
Is there a plan to bump `github.com/go-redis/redis` to latest, as the current version is incompatible.

**Comment by brandur** [comment]
#84 was pitched quite a while ago, but delayed for a long time due to the poor state of maintenance of this project. I've bumped the PR and will try to bring in support as soon as possible.

**Comment by mfridman** [comment]
This issue can likely be closed, as the PR was merged and the latest pinned version in go.mod is v9

https://github.com/throttled/throttled/blob/master/go.mod#L11

**Comment by brandur** [comment]
Yep, resolved now. Thanks!
