### ISSUE TITLE
Unable to use any value but 1 for quantity

### ISSUE THREAD

**Issue by kichik** [throttled/throttled#97]
I'm trying to use this library to throttle my writes into DynamoDB. I have a certain amount of requests per second I can make. I'm trying to write them in batches to reduce latency. Maximum batch size for DynamoDB is 25.

With my first implementation, I used `MaxRate:  throttled.PerSec(myLimit)` and then called `rateLimiter.RateLimit("key", 25)` to report that I'm taking 25 write capacity unit with my batch. But I couldn't get it to work properly. The example below kept printing:

```
2009/11/10 23:00:00 Error rate limiting - bad result: {Limit:1 Remaining:1 ResetAfter:0s RetryAfter:-1ns}
```

I tried different max rates, with and without burst, and various settings for the mem store. But nothing worked. It always says the request was limited and the `retryAfter` value is invalid.

The only thing that worked was to ask for 1 quantity in `RateLimit` and then set `MaxRate` accordingly to capacity divided by 25.

How can I get the code to work with quantity greater than 1?

```go
package main

import (
	"log"

	"github.com/throttled/throttled"
	"github.com/throttled/throttled/store/memstore"
)

func main() {
	// create rate limiter
	store, err := memstore.New(10)
	if err != nil {
		log.Fatal(err)
	}

	quota := throttled.RateQuota{
		MaxRate:  throttled.PerSec(10000),
		MaxBurst: 0,
	}

	rateLimiter, err := throttled.NewGCRARateLimiter(store, quota)
	if err != nil {
		log.Fatal(err)
	}

	// use rate limiter
	limited, details, err := rateLimiter.RateLimit("key", 25)
	if err != nil {
		log.Fatalf("Error rate limiting: %v", err)
	}
	if !limited {
		log.Println("Not limited. Good to go.")
	}
	if details.RetryAfter == -1 {
		log.Fatalf("Error rate limiting - bad result: %+v", details)
	}
}
```

**Comment by brandur** [comment]
Hey @kichik,

Just change your max burst to a non-zero number and you should be good to go:

``` go
	quota := throttled.RateQuota{
		MaxRate:  throttled.PerSec(10000),
		MaxBurst: 25, // this works, but for 10k/sec should probably be higher
	}
```

If you think of your total rate like a bucket that's being refilled at a rate dictated by `MaxRate`, `MaxBurst` is the total size of the bucket.

The implementation will allow a leeway of 1, which is why your example works if you just use a rate of 1, but consider this not recommended — most real uses should be configured with a > 1 maximum burst.

**Comment by brandur** [comment]
Also, remember to use "github.com/throttled/throttled/v2" instead of "github.com/throttled/throttled".

**Comment by kichik** [comment]
Thanks @brandur. Is there any way to do this without burst? I really would like to avoid burst as that doesn't play well with the AWS SDK that has its own throttling handling. Any burst will cause throttling on the server side.

**Comment by brandur** [comment]
There might be some way to tweak the algorithm, but it's been a while since I've really looked closely at it, and I'm not sure off hand. For the time being, I think you'd have to have a max burst at least equal to the minimum action size you intend to use.

**Comment by kichik** [comment]
Will the minimum action size be enough? You mentioned a leeway of 1 is not recommended.

BTW, with burst of 0 and using quantity of 1, I did seem to get the results I was expecting. The rate was fine. I got no throttling.

**Comment by kichik** [comment]
It seems like I hit what you were hinting at after all. It was throttling me too much (50% performance). I had to move to a [different library](https://github.com/uber-go/ratelimit). Thanks for your help!
